plugins {
    id 'com.android.application'
}

android {
    namespace 'io.ugm'
    compileSdk 35

    defaultConfig {
        applicationId 'io.ugm'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/ugm")
        }
    }
}

tasks.register("copyDebugApk", Copy) {
    from(layout.buildDirectory.dir("outputs/apk/debug"))
    into(rootProject.layout.buildDirectory)
    include("*.apk")

    rename { "app-debug.apk" }
}

afterEvaluate {
    tasks.named("assembleDebug").configure {
        finalizedBy("copyDebugApk")
    }
}